GET http://localhost:3500/user-api/users

###
GET http://localhost:3500/user-api/get-user/203

###
POST http://localhost:3500/user-api/create-user
Content-Type: application/json

{
    "name":"pulluru satwik",
    "password":"2993",
    "age":20
}

### 
PUT http://localhost:3500/user-api/update-user
Content-Type: application/json

{
    "name":"satkus",
    "password":"satkus",
    "age":20
}

###
DELETE http://localhost:3500/user-api/delete-user/201